spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:18080
        username: "admin"
        password: "admin"
        instance:
          name: ndgndg91-api-server

  datasource:
    url: jdbc:h2:mem:only-test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: env, beans
